// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OutputTargetFrameworkForProjects
{
    internal sealed partial class Vsix
    {
        public const string Id = "OutputTargetFrameworkForProjects.db9e0bb1-51c6-452a-966c-89b04610c31f";
        public const string Name = "OutputTargetFrameworkForProjects";
        public const string Description = @"Outputs the target framework for every project in the solution to a new text file";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "John J. DeFalco";
        public const string Tags = "";
    }
}
